### ISSUE TITLE
Option to sync selection to CLIPBOARD

### ISSUE THREAD

**Issue by karabaja4** [aperezdc/termite#16]
Hi,

I have this patch that I wrote for my build of termite:

```
--- termite-16.6/subprojects/vte/src/vte.cc	2023-07-02 22:57:30.000000000 +0200
+++ termite-16.6-clipboard/subprojects/vte/src/vte.cc	2023-08-24 19:54:29.282306164 +0200
@@ -6532,7 +6532,7 @@
 		/* Copy only if something was selected. */
                 if (!m_selection_resolved.empty() &&
 		    m_selecting_had_delta) {
-                        widget_copy(vte::platform::ClipboardType::PRIMARY,
+                        widget_copy(vte::platform::ClipboardType::CLIPBOARD,
                                     vte::platform::ClipboardFormat::TEXT);
 			emit_selection_changed();
 		}
```

What it does is it makes all the selections go into CLIPBOARD instead of PRIMARY, which is what I'm used to from xfce4-terminal when its option `Automatically copy selection to clipboard` is enabled.

Would it be possible to add this option to termite config, something like `selection_to_clipboard = true`?

Regards,

Igor

**Comment by aperezdc** [comment]
I think we could plumb this in Termite itself without patching VTE, using the `VteTerminal::selection-changed` signal. 

@karabaja4 I suppose you want the selection to be sent to `CLIPBOARD` when selecting with the mouse, right? Because when using selection mode one can use the `y` key binding (yank) to copy the selection already.

**Comment by aperezdc** [comment]
> I think we could plumb this in Termite itself without patching VTE, using the `VteTerminal::selection-changed` signal.
> 
> @karabaja4 I suppose you want the selection to be sent to `CLIPBOARD` when selecting with the mouse, right? Because when using selection mode one can use the `y` key binding (yank) to copy the selection already.

I managed to implement this in https://github.com/aperezdc/termite/commit/15faf3b7950157b5301797cee67be46b72537e7d and it will be in the next release.

**Comment by karabaja4** [comment]
> I think we could plumb this in Termite itself without patching VTE, using the `VteTerminal::selection-changed` signal.
> 
> @karabaja4 I suppose you want the selection to be sent to `CLIPBOARD` when selecting with the mouse, right? Because when using selection mode one can use the `y` key binding (yank) to copy the selection already.

Correct. Thank you for the implementation!
