### ISSUE TITLE
Update vte to 0.76.0 release

### ISSUE THREAD

**Issue by BarbUk** [aperezdc/termite#17]
Hey @aperezdc, hope you are doing well.

Vte has tagged [the release 0.76.0](https://github.com/GNOME/vte/releases/tag/0.76.0) which come with [several performance improvements from Christian Hergert](https://blogs.gnome.org/chergert/2023/10/03/vte-performance-improvements/).

I've done a local test build of termite with the new tag ([patched vte on my fork](https://github.com/BarbUk/vte/tree/vte-0.76.0-termite)) and it's working without issue.

Could you bump the vte version to 0.76.0 so that we can release a new build to archlinux ?

**Comment by aperezdc** [comment]
Done in commit 649d5d025066d5615e79ebc7fcdb2a0e2833d3ca
