### ISSUE TITLE
Broken for usage on arch linux

### ISSUE THREAD

**Issue by fiskhest** [aperezdc/termite#4]
On ArchLinux, I'm suddenly getting `error while loading shared libraries: libicuuc.so.70: cannot open shared object file: No such file or directory` when trying to launch termite. System is up to date and rebooted. Also tried reinstalling termite to no effect.

```
❯ ldconfig -p | ag libicuuc
	libicuuc.so.71 (libc6,x86-64) => /usr/lib/libicuuc.so.71
	libicuuc.so (libc6,x86-64) => /usr/lib/libicuuc.

❯ pacman -Q | ag termite
termite 16.4-2
termite-terminfo 15-4
```

**Comment by null-git** [comment]
> If packages in the official repositories are updated, you will need to **rebuild** any AUR packages that depend on those libraries.

https://wiki.archlinux.org/title/Arch_User_Repository#Installing_and_upgrading_packages

**Comment by fiskhest** [comment]
I was under the impression reinstalling something rebuilds it, no?

**Comment by fiskhest** [comment]
`makepkg -si` on the PKGBUILD resolved the issue for me. I'm unable to understand why it won't work when I try to manage it through the package manager aura, let's hope it's some aura-specific behavior.
