### ISSUE TITLE
System-specific installation instructions in a wiki page

### ISSUE THREAD

**Issue by marcospb19** [aperezdc/termite#5]
Thanks for bringing this back to life.

A while back I forked a repository to modify an `termite` installation script for Ubuntu and Debian:

https://github.com/marcospb19/termite-install
https://github.com/marcospb19/termite-install/blob/master/termite-install.sh

I no longer use debian-based to test it, but I wonder if this repository could have a wiki page for system-specific installation instructions.

For a platform like Ubuntu, the instructions should specify all the dependencies needed to install the package, and for distros like Arch you could have the AUR helper oneliner.

**Comment by aperezdc** [comment]
I have enabled the wiki pages support in the project settings, so I think anybody who may want to try and write such a page can do it now&mdash;I do not have time for that at the moment, but collaborations from other people are always welcome 👩🏼‍🎤
