### ISSUE TITLE
[Feature Request | Bug Report] Implement Clear and fix Clear and Reset

### ISSUE THREAD

**Issue by ifohancroft** [aperezdc/termite#8]
This has been discussed in the original Termite repo previously, but I thought it would be useful to also have it here, in-case someone who has the skills wants to implement it.

- Clear: Scrolls everything up until you get one full clear screen and shows the prompt again, but you can scroll back to the previous output

    This is currently missing from Termite.

- Clear and Reset: Clears everything up from the scrollback buffer so you get a clear screen, and shows the prompt again. There is nothing to scroll back to

    This is currently implemented in Termite, but the prompt isn't being shown again.

The current reset and clear implementation calls `vte_terminal_reset` [here](https://github.com/aperezdc/termite/blob/main/termite.cc#L1088), which is defined [here](https://github.com/aperezdc/vte/blob/master/src/vtegtk.cc#L4438) (function prototype (I think) found [here](https://github.com/aperezdc/vte/blob/master/src/vte/vteterminal.h#L393)).

It's also being called inside the definition of another function in VTE, found [here](https://github.com/aperezdc/vte/blob/master/src/app/app.cc#L2029), but I couldn't find anything inside Termite or even VTE to ever call that other function anywhere.

My understanding is:

1. To fix the prompt not showing up, either Termite's switch case where `vte_terminal_reset` is called needs to be extended, or the `vte_terminal_reset` function itself, depending on who's responsible for calling/showing the shell prompt.
2. To implement clear, `vte_terminal_reset` can be called, giving it false for the second argument.

**Comment by adamency** [comment]
I don't know what you're talking about. Both things you're asking about are already there and there's no prompt issue at all.

Point 1, i.e. "Clear" => `Ctrl+L`
Point 2, i.e. "Clear & Reset" => `clear`

Both perfectly work and show the prompt very well.

**Comment by ifohancroft** [comment]
> I don't know what you're talking about. Both things you're asking about are already there and there's no prompt issue at all.
> 
> Point 1, i.e. "Clear" => `Ctrl+L` Point 2, i.e. "Clear & Reset" => `clear`
> 
> Both perfectly work and show the prompt very well.

`clear` is not from the terminal. It's from the shell.
Ctrl+Shift+l works, but it doesn't show the prompt again on my end.

**Comment by aperezdc** [comment]
@ifohancroft The shell is responsible to show the prompt, and unfortunately a terminal emulator does _not_ have any kind of control over which programs are running inside it. This means that from the point of view of Termite/VTE all we know is “we have spawn a shell when creating this terminal” but that's all, the shell could have spawned something else (a text editor, an email client, etc.) or even itself may have been replaced (using the shell `exec` built-in) and there is no standard way of telling a program “please go and repaint yourself after the terminal emulator has been reset”.
